### ISSUE TITLE
Highlight editable part of the banner

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/banner#1]
- [x] Animation + look & feel
 - [ ] How does an element declares it is editable? (`data-no-config` ?)

**Comment by dfosco** [comment]
@breno, how does the component declares it's editable — is it with data-no-config?

**Comment by dfosco** [comment]
@brenoc

This is how a component is styled and animated as its state changes. These selectors currently live on `BannerEditMode.less`

```
.v-banner {
  &[data-no-config=false] {
    outline: none;
    outline-offset: none;
    transition: outline 0.4s cubic-bezier(1, 0.12, 0, 1.07) 0.4s;
  }

  &[data-no-config=true] {
    outline: 4px solid lighten(@red-matter, 10%);
    outline-offset: -4px;
    transition: outline 0.4s cubic-bezier(1, 0.12, 0, 1.07) 0.4s,;
  }
}
```

I'm thinking we should move these css properties into `storefront-editor` to isolate them from 3rd party component developers — otherwise they would be able to change these styles that, in the end, are not part of the component, but part of the admin interface.

What do you think would be the best way to achieve this?

**Comment by brenoc** [comment]
About
> How does an element declares it is editable? (data-no-config)

What do you think of this instead:

```html
<div classNames="v-banner-editmode v-storefront-editable">
  My component
</div>
```

**Comment by brenoc** [comment]
Or just `storefront-editable`

**Comment by brenoc** [comment]
I think using the `data-no-config` or `data-storefront=true' would make us write the following CSS:

```css
*[data-no-config=false] {
    outline: none;
    outline-offset: none;
    transition: outline 0.4s cubic-bezier(1, 0.12, 0, 1.07) 0.4s;
  }

 *[data-no-config=true] {
   outline: 4px solid lighten(@red-matter, 10%);
   outline-offset: -4px;
   transition: outline 0.4s cubic-bezier(1, 0.12, 0, 1.07) 0.4s,;
 }
```

I don't think that's performant.
